### ISSUE TITLE
Conda install stuck solving environment for python=3.8

### ISSUE THREAD

**Issue by TankredO** [AGOberprieler/GinJinn2#1]
Installation via `conda install` stuck at solving environment when trying to install in an environment with Python 3,8.

The workaround for now is to install GinJinn2 into an environment with Python 3.7:

```Bash
conda create -n test python=3.7
conda activate test
conda install -c agoberprieler -c conda-forge -c pytorch cudatoolkit=10.1 ginjinn2
```

**Comment by mareikedaubert** [comment]
I also encountered the issue of the installation getting stuck. The solution above did not solve it. However, it worked with an alternative solver. 
<pre>conda create -n test python=3.7
conda activate test
conda install -c agoberprieler -c conda-forge -c pytorch cudatoolkit=10.1 ginjinn2 --experimental-solver=libmamba<pre>

**Comment by ulilautenschlager** [comment]
Thanks for the suggestion!
In some cases, the installation process is currently extremely slow (taking several hours in the extreme) while others only need a few minutes. So far, we haven't found the reason for these huge discrepancies, but using mamba or conda+libmamba (which is supposed to become conda's new default solver) seems to be a good workaround. In my case, using mamba instead of conda speeds up the installation immensely: 4 h -> 1 min for Python 3.7 and 1 h -> 1.5 min for Python 3.8.
